site:
  siteURL: https://www.ybjun.com/
  title: 月半菌的Blog
  subtitle: 用通俗的语言，传递实用的干货，还有好玩的资源，尽在月半菌!
  lang: zh
  translate:
    enable: false
    service: client.edge
    showSelectTag: false
    autoDiscriminate: true
    ignoreClasses:
      - ignore
      - banner-title
      - banner-subtitle
    ignoreTags:
      - script
      - style
      - code
      - pre
  timeZone: 8
  font:
    LXGW WenKai Screen:
      src: https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-web/style.css
      family: LXGW WenKai Screen
  themeColor:
    hue: '30'
  defaultTheme: system
  wallpaper:
    mode: banner
    src:
      desktop:
        - /assets/images/desktopWallpaper_1.webp
        - /assets/images/desktopWallpaper_2.webp
        - /assets/images/desktopWallpaper_3.webp
        - /assets/images/desktopWallpaper_4.webp
        - /assets/images/desktopWallpaper_5.webp
        - /assets/images/desktopWallpaper_6.webp
        - /assets/images/desktopWallpaper_7.webp
        - /assets/images/desktopWallpaper_8.webp
      mobile:
        - /assets/images/mobileWallpaper_1.webp
        - /assets/images/mobileWallpaper_2.webp
        - /assets/images/mobileWallpaper_3.webp
        - /assets/images/mobileWallpaper_4.webp
        - /assets/images/mobileWallpaper_5.webp
        - /assets/images/mobileWallpaper_6.webp
        - /assets/images/mobileWallpaper_7.webp
        - /assets/images/mobileWallpaper_8.webp
    position: center
    carousel:
      enable: true
      interval: 3.6
      kenBurns: true
    banner:
      homeText:
        enable: true
        title: 月半菌的Blog
        subtitle:
          - Illuminate Our Paths
        typewriter:
          enable: true
          speed: 111
          deleteSpeed: 51
          pauseTime: 3000
      credit:
        enable: true
        text: 背景图来自 Bing
        url: https://www.bing.com
      navbar:
        transparentMode: semifull
      waves:
        enable: true
        performanceMode: false
    fullscreen:
      zIndex: -1
      opacity: 0.9
      blur: 1
      navbar:
        transparentMode: semi
  loadingOverlay:
    enable: true
    title:
      enable: true
      content: LOADING
      interval: 1.5
    spinner:
      enable: true
      interval: 1.5
  favicon: []
  bangumi:
    userId: your-bangumi-id
  generateOgImages: false
umami:
  enabled: false
  baseUrl: https://api.umami.is
  apiKey: ''
  scripts: ''
navbar:
  links:
    - Home
    - Archive
    - name: 相册
      url: /gallery/
      icon: material-symbols:photo-library
    - name: 胖哥出品
      icon: material-symbols:widgets-rounded
      description: 胖哥打造的软件合集
      children:
        - name: 壁纸库
          url: https://dailywall.ybjun.com/
          icon: material-symbols:imagesmode
        - name: 歌词大师
          url: https://lrc.ybjun.com/
          icon: material-symbols:music-note
        - name: 胖哥WinPE
          url: >-
            https://mp.weixin.qq.com/mp/homepage?__biz=Mzg4NDYyOTA2NA==&hid=1&sn=86e8a70e45fc81e022c0d9d02dc83b35&scene=18
          icon: mdi:microsoft-windows
        - name: 更多
          url: >-
            https://mp.weixin.qq.com/mp/appmsgalbum?__biz=Mzg4NDYyOTA2NA==&action=getalbum&album_id=1954109779866337283#wechat_redirect
          icon: material-symbols:read-more
    - name: 朋友们
      url: /friends/
      icon: material-symbols:group
    - About
sidebar:
  components:
    left:
      - type: profile
        position: top
      - type: announcement
        position: top
      - type: categories
        position: sticky
        responsive:
          collapseThreshold: 5
      - type: tags
        position: sticky
        responsive:
          collapseThreshold: 20
    right:
      - type: statistics
        position: top
      - type: toc
        position: sticky
        customProps:
          depth: 3
      - type: visitorinfo
        position: sticky
profile:
  avatar: /assets/images/avatar.jpg
  name: 月半菌
  bio: 用通俗的语言，传递实用的干货，还有好玩的资源，尽在月半菌!
  links:
    - name: 微信公众号
      icon: fa6-brands:weixin
      url: '#wechat-qrcode'
    - name: Bilibili
      icon: fa6-brands:bilibili
      url: https://space.bilibili.com/306479391
    - name: 知乎
      icon: fa6-brands:zhihu
      url: https://www.zhihu.com/people/elliot-69-70
    - name: 图虫摄影网
      icon: material-symbols:camera
      url: https://tuchong.com/25406319
    - name: 邮箱
      icon: material-symbols:mail
      url: 'mailto:yuebanjun666@outlook.com '
announcement:
  title: 公告
  content: 欢迎来到月半菌的博客！博客于2026年春节正式上线！欢迎提出宝贵意见！
  closable: true
  link:
    enable: true
    text: 了解更多
    url: /about/
    external: false
post:
  showLastModified: true
  showCoverInContent: false
  expressiveCode:
    theme: github-dark
  license:
    enable: true
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  comment:
    enable: true
    twikoo:
      envId: https://twikoo.vercel.app
      lang: en
footer:
  enable: false
  customHtml: ''
particle:
  enable: true
  particleNum: 8
  limitTimes: -1
  size:
    min: 0.3
    max: 0.9
  opacity:
    min: 0.3
    max: 0.9
  speed:
    horizontal:
      min: -0.9
      max: 0.9
    vertical:
      min: 0.15
      max: 0.3
    rotation: 0.12
    fadeSpeed: 0.12
  zIndex: 100
musicPlayer:
  enable: true
  mode: meting
  meting:
    meting_api: https://api.i-meto.com/meting/api
    server: netease
    type: playlist
    id: '2161912966'
  local:
    playlist:
      - id: 1
        title: 深海之息
        artist: Youzee Music
        cover: >-
          https://p1.music.126.net/PhKOqFtljgHDDpKYM2ADUA==/109951169858309716.jpg
        url: assets/music/深海之息.m4a
        duration: 146
  autoplay: false
pio:
  enable: false
  models:
    - /pio/models/pio/model.json
  position: left
  width: 280
  height: 250
  mode: draggable
  hiddenOnMobile: true
  dialog:
    welcome: Welcome!
    touch:
      - What are you doing?
      - Stop touching me!
      - Don't bully me like that!
      - (｡í _ ì｡)
    home: Click here to go back to homepage!
    skin:
      - Want to see my new outfit?
      - The new outfit looks great~
    close: See you next time~
    link: https://nav.kungal.org
